name: Build and push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CONTEXT_DIR: .
  IMAGE_TAG: v1.0
  RUNNER_VERSION: 0.4.0
  DOCKERFILE: Dockerfile
  DOCKER_NAMESPACE: jimmyb
  DOCKER_IMAGE_NAME: peertube-runner-gpu

jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: check repository
        uses: actions/checkout@v4
        with:
          lfs: "true"

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and push docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.CONTEXT_DIR }}
          push: true
          tags: |
            ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.RUNNER_VERSION }}
            ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          file: ${{ env.DOCKERFILE }}

      - name: login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push docker image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.CONTEXT_DIR }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.RUNNER_VERSION }}
            ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          file: ${{ env.DOCKERFILE }}

      - name: login to custom Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CUSTOM_REGISTRY_URL }}
          username: ${{ secrets.CUSTOM_REGISTRY_USERNAME }}
          password: ${{ secrets.CUSTOM_REGISTRY_PASSWORD }}

      - name: build and push docker image to custom registry
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.CONTEXT_DIR }}
          push: true
          tags: |
            ${{ secrets.CUSTOM_REGISTRY_URL }}/${{ env.CUSTOM_REGISTRY_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.RUNNER_VERSION }}
            ${{ secrets.CUSTOM_REGISTRY_URL }}/${{ env.CUSTOM_REGISTRY_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          file: ${{ env.DOCKERFILE }}
